name: 'Trigger Azure Virtual Machine Scale Set Rolling Update'
description: 'triggers a rolling update for azure virtual machine scale set'
inputs: 
  resourceGroup:
    description: 'name of resource group for virtual machine scale set'
    required: true 
  tenantId:
    description: 'tenant id'
    required: true
  clientId:
    description: 'client id'
    required: true 
  clientSecret:
    description: 'client secret'
    required: true 
  scaleSetName: 
    description: 'scale set name'
    required: true
outputs:
  resourceGroupId: 
    description: 'the ID of the resource group that was found'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args: 
    - ${{ inputs.resourceGroup }}
    - ${{ inputs.tenantId }}
    - ${{ inputs.clientId}}
    - ${{ inputs.clientSecret}}
    - ${{ inputs.scaleSetName }}