name: 'Trigger Azure Virtual Machine Scale Set Rolling Update'
description: 'triggers a rolling update for azure virtual machine scale set'
inputs: 
  resourceGroup:
    description: 'name of resource group for virtual machine scale set'
    required: true 
  tenantId:
    description: 'tenant id'
    required: true
  clientId:
    description: 'client id'
    required: true 
  clientSecret:
    description: 'client secret'
    required: true 
  scaleSetName: 
    description: 'scale set name'
    required: true
  subscriptionId: 
    description: 'Azure subscription ID'
runs:
  using: 'docker'
  image: 'lbabay.azurecr.io/az-vmss-rolling-update:v1.0'
  args: 
    - ${{ inputs.resourceGroup }}
    - ${{ inputs.tenantId }}
    - ${{ inputs.clientId}}
    - ${{ inputs.clientSecret}}
    - ${{ inputs.scaleSetName }}
    - ${{ inputs.subscriptionId }}
    