name: 'Trigger Azure Virtual Machine Scale Set Rolling Update'
description: 'triggers a rolling update for azure virtual machine scale set'
inputs: 
  resourceGroup:
    description: 'name of resource group for virtual machine scale set'
    required: true 
outputs:
  resourceGroupId: 
    description: 'the ID of the resource group that was found'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args: 
    - ${{ inputs.test }}