on: 
  - push
jobs: 
  helloworld:
    runs-on: ubuntu-latest
    name: first job 
    steps:
      - name: checkout 
        uses: actions/checkout@v3 

      - name: azure virtual machine scale set trigger rolling update  
        uses: ./ 
        id: test 
        env:
          resourceGroup: 'aks-demos'
          scaleSetName: 'tes'
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
          AZURE_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
          imageId: "/subscriptions/f80dea2d-81bb-442f-a102-d86eb72cb7d6/resourceGroups/aks-demos/providers/Microsoft.Compute/images/prod-frontend-new"
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
          
      - name: get the output 
        run: echo ${{ steps.test.outputs.resourceGroupId }}