on: 
  - push
jobs: 
  helloworld:
    runs-on: ubuntu-18.04
    name: first job 
    steps:
      - name: checkout 
        uses: actions/checkout@v3 

      - name: hello world action 
        uses: ./ 
        id: test 
        with: 
          resourceGroup: 'mern'
          tenantId: ${{ secrets.AZURE_TENANT_ID }}
      - name: get the output 
        run: echo ${{ steps.test.outputs.resourceGroupId }}