on: 
  - push
jobs: 
  helloworld:
    runs-on: ubuntu-18.04
    name: first job 
    steps:
      - name: checkout 
        uses: actions/checkout@v3 
      - name: hello world action 
        uses: ./ 
        id: test 
        with: 
          test: 'landon babay'
      - name: get the output 
        run: echo ${{ steps.test.outputs.hey }}