on: 
  - push
jobs: 
  helloworld:
    runs-on: ubuntu-18.04
    name: first job 
    steps:
      - name: checkout 
        uses: actions/checkout@v3 

      - name: azure virtual machine scale set trigger rolling update  
        uses: ./ 
        id: test 
        env:
          resourceGroup: 'aks-demo'
          scaleSetName: 'test'
          tenantId: ${{ secrets.AZURE_TENANT_ID }}
          clientId: ${{secrets.AZURE_CLIENT_ID}}
          clientSecret: ${{secrets.AZURE_CLIENT_SECRET}}
          imageId: "/subscriptions/f80dea2d-81bb-442f-a102-d86eb72cb7d6/resourceGroups/aks-demos/providers/Microsoft.Compute/images/prod-frontend-initial"
          
          
      - name: get the output 
        run: echo ${{ steps.test.outputs.resourceGroupId }}